-- CreateTable
CREATE TABLE `NMU` (
    `NMUId` INTEGER NOT NULL AUTO_INCREMENT,
    `NMUDesc` VARCHAR(255) NULL,
    `ItemNeeded` BOOLEAN NOT NULL DEFAULT false,
    `VersionNeeded` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`NMUId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NMUItem` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `itemName` VARCHAR(255) NOT NULL,
    `nmuId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `NMUItem` ADD CONSTRAINT `NMUItem_nmuId_fkey` FOREIGN KEY (`nmuId`) REFERENCES `NMU`(`NMUId`) ON DELETE CASCADE ON UPDATE CASCADE;
